### ISSUE TITLE
Calls to IVR and conference are not being shown

### ISSUE THREAD

**Issue by fmateo05** [baloeng/monster-ui-recordings#1]
Hi. I was testing the app recently; and it only records calls among endpoints (users and devices). I would like to check recordings when calls come to ivr and conferences

Thanks in advance

**Comment by baloeng** [comment]
Hi @fmateo05, if I understand your question, you mean recorded calls from IVR and conferences are not displayed right?. I think these type of recordings are tied to the account and not users/devices.

I'll have to add that option to the app.

Thanks for bringing it up.

**Comment by fmateo05** [comment]
On the account settings level there are nested options for enable call-recordings on that sense. (some extra information that may help, just in case)

**Comment by baloeng** [comment]
Made some changes to the app. Now, you should be able see IVRs, conference, etc recordings.

Still need to add some features to the app where account, users and device recordings settings can be configured.

**Comment by baloeng** [comment]
I've now added account recordings setting @fmateo05
